// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tzfuszsoqgyvzxvqeqeb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6ZnVzenNvcWd5dnp4dnFlcWViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1OTk3NjUsImV4cCI6MjA3MDE3NTc2NX0.KtO4bPiMi5K5uI7ZFW_6lkYXgzOjwHRQ3TD6rBLXgro";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});